import pyowm
owm = pyowm.OWM('0eda0646e5abc58261f99346b3c98755')
observation = owm.weather_at_place("jaipur,India")
w = observation.get_weather()
temperature = w.get_temperature('celsius')
tomorrow = pyowm.timeutils.tomorrow()
wind = w.get_wind()
print(w)
print(wind)
print(temperature)
print(tomorrow)
